sudo: required

language: c

services:
  - docker

before_install:
  - docker build -t simavr .

install:
  - docker run -v $TRAVIS_BUILD_DIR:/build simavr all

script:
  - docker run -v $TRAVIS_BUILD_DIR:/build simavr test &
    PID=$! ;
    sleep 10 ;
    kill -TERM $PID ;
    true
